version: '3.8'  

services:
  web:
    build: .
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://usuario:senha@db/escola
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: usuario  # Usuário 
      POSTGRES_PASSWORD: senha  # Senha 
      POSTGRES_DB: escola           
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario -d escola"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: